// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhljmEdMG2rtGe0zyDVuoGtHCdqVIRn70',
    appId: '1:450834984965:web:58191a1caa5929aab4ec6c',
    messagingSenderId: '450834984965',
    projectId: 'flutter-test-ae498',
    authDomain: 'flutter-test-ae498.firebaseapp.com',
    storageBucket: 'flutter-test-ae498.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhB0wCp86tNi235DW2p4Uyj431XfyD06I',
    appId: '1:450834984965:android:639f9ff6887f6647b4ec6c',
    messagingSenderId: '450834984965',
    projectId: 'flutter-test-ae498',
    storageBucket: 'flutter-test-ae498.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8PvK4cnb2qgnZDHCHlwc0RnCY1w4nZEQ',
    appId: '1:450834984965:ios:239ce5188c37d7bfb4ec6c',
    messagingSenderId: '450834984965',
    projectId: 'flutter-test-ae498',
    storageBucket: 'flutter-test-ae498.appspot.com',
    iosClientId:
        '450834984965-opg0v58b0hjf52477rt3i834aacg3p2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseCrud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8PvK4cnb2qgnZDHCHlwc0RnCY1w4nZEQ',
    appId: '1:450834984965:ios:69d1b042c9ca02a1b4ec6c',
    messagingSenderId: '450834984965',
    projectId: 'flutter-test-ae498',
    storageBucket: 'flutter-test-ae498.appspot.com',
    iosClientId:
        '450834984965-6ikeffju07tts3s6osrqmi18anobd5q8.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseCrud.RunnerTests',
  );
}
